---
title: "Implicancia de Tenacibaculosis en la mortalidad en Salmón Atlántico"
author: "Constanza Pino Ajenjo"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyverse)
library(kableExtra)
library(pander)
library(DT)

```

Descripción del problema a resorver: 
La Tenacibaculosis es una infección bacteriana cuya etiología Tenacibaculum maritimus (Flexibacter maritimus) afecta principalmente al cultivo de Salmón del Atlántico. Principalmente se evidencian lesiones macroscópicas en la superficie del cuerpo; úlceras, necrosis, boca erosionada, aletas deshilachadas y cola con pudrición,
y a veces necrosis en las branquias y los ojos (congestión choroidal y hemorragia sub-choroidal, a
veces con ruptura del ojo). Por tal motivo, es importante determinar la implicancia de la mortalidad causada por Tenacibaculosis en agua de mar.

Variables de estudio: peso promedio y mortalidad 
Factor a analizar: mortalidad por Tenacibaculosis
Número total de observaciones: 13
